apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: dev-environment
spec:
  type: {{ .Values.service.type | default "ClusterIP" }} 
  selector:
    app: weather # This MUST match the label in your deployment
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80