service:
  type: LoadBalancer
  port: 80
replicaCount: 2
storage:
  size: 1Gi
image:
  repository: weatherappregistry2026.azurecr.io/weather-api
  tag: "0e919c9dc9512dc2fab22d06bb871989993ebe2e"

tag: "0e919c9dc9512dc2fab22d06bb871989993ebe2e"
