apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: weather-kv-secrets
  namespace: dev-environment
spec:
  provider: azure
  parameters:
    useWorkloadIdentity: "true"
    keyvaultName: "kv-weather-gitops-grb2s"
    tenantId: "13835650-676a-4d8c-8bfe-b4ddeb87e0ae"
    objects: |
      array:
        - |
          objectName: API-KEY
          objectType: secret