apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-db-pvc
  namespace: dev-environment
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default